## Airflow service parameters
##
service:
  ## @param service.type Airflow service type
  ##
  type: LoadBalancer
  loadBalancerIP: 10.108.94.123
worker:
## @param extraVolumes Optionally specify extra list of additional volumes for the all the Airflow pods
##
  extraVolumes:
    - name: requirements
      configMap:
        name: airflow-requirements
## @param extraVolumeMounts Optionally specify extra list of additional volumeMounts for all the Airflow pods
##
  extraVolumeMounts:
    - name: requirements
      mountPath: /bitnami/python/requirements.txt
      subPath: requirements.txt

  ## Configure Airflow web pods Security Context
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
  ## @param web.podSecurityContext.enabled Disabled Airflow web pods' Security Context
  podSecurityContext:
    enabled: false
  ## Configure Airflow web containers (only main one) Security Context
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
  ## @param web.containerSecurityContext.enabled Disbaled Airflow web containers' Security Context
  containerSecurityContext:
    enabled: false
scheduler:
  ## @param extraVolumes Optionally specify extra list of additional volumes for the all the Airflow pods
  ##
  extraVolumes:
    - name: requirements
      configMap:
        name: airflow-requirements
  ## @param extraVolumeMounts Optionally specify extra list of additional volumeMounts for all the Airflow pods
  ##
  extraVolumeMounts:
    - name: requirements
      mountPath: /bitnami/python/requirements.txt
      subPath: requirements.txt
  ## Configure Airflow web pods Security Context
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
  ## @param web.podSecurityContext.enabled Disabled Airflow web pods' Security Context
  podSecurityContext:
    enabled: false
  ## Configure Airflow web containers (only main one) Security Context
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
  ## @param web.containerSecurityContext.enabled Disbaled Airflow web containers' Security Context
  containerSecurityContext:
    enabled: false
web:
  ## @param extraVolumes Optionally specify extra list of additional volumes for the all the Airflow pods
  ##
  extraVolumes:
    - name: requirements
      configMap:
        name: airflow-requirements
  ## @param extraVolumeMounts Optionally specify extra list of additional volumeMounts for all the Airflow pods
  ##
  extraVolumeMounts:
    - name: requirements
      mountPath: /bitnami/python/requirements.txt
      subPath: requirements.txt
  ## Configure Airflow web pods Security Context
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
  ## @param web.podSecurityContext.enabled Disabled Airflow web pods' Security Context
  podSecurityContext:
    enabled: false
  ## Configure Airflow web containers (only main one) Security Context
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
  ## @param web.containerSecurityContext.enabled Disbaled Airflow web containers' Security Context
  containerSecurityContext:
    enabled: false

git:
  ## Get DAG files from git repositories
  ## @param git.dags.enabled Enable in order to download DAG files from git repositories.
  ## @param git.dags.repositories [array] Array of repositories from which to download DAG files
  ##
  dags:
    enabled: true
    ## Name for repositories can be anything unique and must follow same naming conventions as kubernetes.
    ## Kubernetes resources can have names up to 253 characters long. The characters allowed in names are:
    ## digits (0-9), lower case letters (a-z), -, and .
    ## Example:
    ##   - repository: https://github.com/myuser/myrepo
    ##     branch: main
    ##     name: my-dags
    ##     path: /
    ##
    repositories:
      - repository: "https://github.com/babaksit/mlops-e2e"
        ## Branch from repository to checkout
        ##
        branch: "develop"
        ## An unique identifier for repository, must be unique for each repository
        ##
        name: "iris_sklearn"
        ## Path to a folder in the repository containing the dags
        ##
        path: "/pipeline/dags"


## @section Airflow metrics parameters
metrics:
  ## @param metrics.enabled Whether or not to create a standalone Airflow exporter to expose Airflow metrics
  ##
  enabled: true
  ## Prometheus Operator ServiceMonitor configuration
  ##
  serviceMonitor:
    ## @param metrics.serviceMonitor.enabled if `true`, creates a Prometheus Operator ServiceMonitor (requires `metrics.enabled` to be `true`)
    ##
    enabled: true
    ## @param metrics.serviceMonitor.interval Interval at which metrics should be scraped
    ## ref: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#endpoint
    ##
    interval: ""
    ## @param metrics.serviceMonitor.scrapeTimeout Timeout after which the scrape is ended
    ## ref: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#endpoint
    ##
    scrapeTimeout: ""
