
# Disable tracking server password
tracking: 
  auth:
    enabled: false

metrics:
    ## @param tracking.metrics.enabled Enable the export of Prometheus metrics
    ##
    enabled: true
    ## Prometheus Operator ServiceMonitor configuration
    ##
    serviceMonitor:
      ## @param tracking.metrics.serviceMonitor.enabled if `true`, creates a Prometheus Operator ServiceMonitor (also requires `metrics.enabled` to be `true`)
      ##
      enabled: true
      ## @param tracking.metrics.serviceMonitor.interval Interval at which metrics should be scraped.
      ## ref: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#endpoint
      ## e.g:
      ## interval: 10s
      ##
      interval: "30s"
      ## @param tracking.metrics.serviceMonitor.scrapeTimeout Timeout after which the scrape is ended
      ## ref: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#endpoint
      ## e.g:
      ## scrapeTimeout: 10s
      ##
      scrapeTimeout: "30s"
